### PR TITLE
cedric: add TARGET_PROVIDES_QTI_TELEPHONY_JAR

### PR DESCRIPTION
**Pull request by krumboeck**
This patch should solve a conflict with qti-telephony-common.
Further infos: https://github.com/LineageOS/android_hardware_lineage_telephony

### CODE REVIEW

**Comment by pgaskin** [comment]
Works for me.

**Comment by pgaskin** [comment]
@Sohamlad7 Are you planning to update cedric to Pie once LineageOS is updated?

Also, are you planning to release a new build of 15.1? I've been building it myself every 2 weeks (branch lineage-15.1-64) and it's been pretty stable (other than some delay starting the camera). The recent changes and additions in LineageOS have been pretty useful. [Here](https://transfer.sh/fOVh9/lineage-15.1-20180810-UNOFFICIAL-cedric.zip) is my latest build (using test-keys).

**Comment by KalilDev** [comment]
@geek1011 I'm the one maintaining Cedric RN. I made a treble build, but I've yet to make a non treble build. This is on hold until I finish making my common trees from scratch and unifying Cedric and Potter. if you want to check my work, look at my GitHub and at the Motorola-Common github

**Comment by pgaskin** [comment]
Thanks for the info. Your work looks good so far. As for treble, is it stable right now?

**Comment by KalilDev** [comment]
Only issues are camera not being able to record and the Moto actions app not being able to change settings on the fingerprint gestures. Both issues will be fixed with the Potter unification, and if it still doesn't work I'll fix it.

**Comment by pgaskin** [comment]
OK. I will probably try out treble. Do I just build and flash a build from the treble branch then flash a generic image over it? Also, what should the partition table look like?

Edit: Based on [this](https://github.com/Motorola-Common/android_device_motorola_cedric/commit/c62f3e18ea073a67b1e21af7a82ffceef67b60e3#diff-78ec901c9c29ef6a20b79592fd93f941R42) and the output of `cat /proc/partitions`, it seems like you are using the oem partition (`/dev/block/platform/soc/7824900.sdchi/by-name/oem` -> `/dev/mmcblk0p51`) as the vendor partition for treble. Does it need to be formatted?

**Comment by KalilDev** [comment]
nope, block based zips overrides the entire partition to be exact down to the zeroes. if you want info on how to install you can check my XDA thread

**Comment by pgaskin** [comment]
OK, thanks. I completely missed that thread.

**Pull request merged**
