### PR TITLE
cedric: enable OTA

### PR DESCRIPTION
**Pull request by JarlPenguin**

### CODE REVIEW

**Comment by JarlPenguin** [comment]
Note: doesn't actually install updates correctly, might need to patch the OTA app itself. Downloads, can't flash due to missing Digest file (even with verification disabled)

**Comment by mvaisakh** [comment]
Why? This is really useless.

**Comment by JarlPenguin** [comment]
@mvaisakh found out that if we ship signed builds it works (flashing)

**Comment by Sohamlad7** [comment]
i also find this useless

**Comment by JarlPenguin** [comment]
Sure, if you don't care about OTA updates. It works quite well for us.

**Pull request closed without merging**
