### PR TITLE
Cam Video

### PR DESCRIPTION
**Pull request by kiam001**
fixes the videos that can be made with the default camara

### CODE REVIEW

**Comment by Sohamlad7** [comment]
what cam video.. video is working fine

**Comment by kiam001** [comment]
Open default cam make a Video after stop the Video hangs the cam this options fix that

**Comment by mvaisakh** [comment]
Video works without this commit. It's useless.

**Comment by JarlPenguin** [comment]
@kiam001 open isn't default 🤔

**Comment by Sohamlad7** [comment]
Default camera is working perfectly for me and for others just now tested and if this patch is for third party apps then I'm not gonna support it for now

**Comment by kiam001** [comment]
Try to Make a Video

**Comment by kiam001** [comment]
I test it again when it not works reopen it

**Pull request closed without merging**
