### PR TITLE
Fixed call recording overlay

### PR DESCRIPTION
**Pull request by pgaskin**
The path to the res/values file was incorrect.

I have made a build including this change here: [geek1011/android_device_motorola_cedric:custom/build/lineage-16.0-20190806-UNOFFICIAL-cedric](https://github.com/geek1011/android_device_motorola_cedric/releases/tag/custom%2Fbuild%2Flineage-16.0-20190806-UNOFFICIAL-cedric).

### CODE REVIEW

**Comment by pgaskin** [comment]
Note that even though the button shows now, it doesn't seem to actually work. With the audio source set to 1 (MIC, the default), it fails with error -38, and with the audio source set to 4 (VOICE_CALL) with the CAPTURE_AUDIO_OUTPUT permission granted, it fails with error -22.

Here's the logcat for the last one:
```
08-06 12:58:49.640   676  5995 W StagefrightRecorder: stop while neither recording nor paused
08-06 12:58:49.651   676  5991 W StagefrightRecorder: Intended audio sample rate (8000) is too small and will be set to (16000)
08-06 12:58:49.654   517   596 E APM::AudioPolicyEngine: getDeviceForInputSource() no default device defined
08-06 12:58:49.655   517   596 W APM_AudioPolicyManager: getInputForAttr() could not find device for source 4
08-06 12:58:49.655   517   596 E AudioFlinger: createRecord() checkRecordThread_l failed
08-06 12:58:49.655   676  5991 E IAudioFlinger: createRecord returned error -22
08-06 12:58:49.655   676  5991 E AudioRecord: AudioFlinger could not create record track, status: -22
08-06 12:58:49.657   676  5991 E StagefrightRecorder: audio source is not initialized
08-06 12:58:49.657  7958  7969 E MediaRecorder: start failed: -2147483648
08-06 12:58:49.658  7958  7969 W CallRecorderService: Could not start recording for file /storage/emulated/0/CallRecordings/4443_190806_125849635.amr
08-06 12:58:49.658  7958  7969 W CallRecorderService: java.lang.RuntimeException: start failed.
08-06 12:58:49.658  7958  7969 W CallRecorderService: 	at android.media.MediaRecorder.start(Native Method)
08-06 12:58:49.658  7958  7969 W CallRecorderService: 	at com.android.dialer.callrecord.impl.CallRecorderService.startRecordingInternal(CallRecorderService.java:165)
08-06 12:58:49.658  7958  7969 W CallRecorderService: 	at com.android.dialer.callrecord.impl.CallRecorderService.access$400(CallRecorderService.java:43)
08-06 12:58:49.658  7958  7969 W CallRecorderService: 	at com.android.dialer.callrecord.impl.CallRecorderService$1.startRecording(CallRecorderService.java:75)
08-06 12:58:49.658  7958  7969 W CallRecorderService: 	at com.android.dialer.callrecord.ICallRecorderService$Stub.onTransact(ICallRecorderService.java:57)
08-06 12:58:49.658  7958  7969 W CallRecorderService: 	at android.os.Binder.execTransact(Binder.java:731)
08-06 12:58:49.658  7958  7969 W CallRecorderService: Deleting failed recording /storage/emulated/0/CallRecordings/4443_190806_125849635.amr
08-06 12:58:49.659   676  5991 W StagefrightRecorder: stop while neither recording nor paused
```

**Comment by JarlPenguin** [comment]
+1

**Comment by Sohamlad7** [comment]
thank you for the contribution

**Comment by pgaskin** [comment]
Do you think the issues with the call recording are due to missing configs, old blobs, or selinux denials (I've noticed quite a few of those recently, and will be fixing them when I have time)?

**Pull request merged**
